version: "3"
services:
  reverseproxy:
      image: yfandino/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: yfandino/user
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST 
      UDAGRAM_REGION: $UDAGRAM_REGION 
      UDAGRAM_PROFILE: $UDAGRAM_PROFILE 
      UDAGRAM_BUCKET: $UDAGRAM_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  backend-feed:
    image: yfandino/feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST 
      UDAGRAM_REGION: $UDAGRAM_REGION 
      UDAGRAM_PROFILE: $UDAGRAM_PROFILE 
      UDAGRAM_BUCKET: $UDAGRAM_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  frontend:
    image: yfandino/frontend
    ports:
      - "8100:80"
